[
theme
]

# Primary accent for interactive elements
primaryColor = '#DAD873'

# Background color for the main content area
backgroundColor = '#454D66'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#31333F'

# Color used for almost all text
textColor = '#309975'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
